### ISSUE TITLE
PowerPoint issue

### ISSUE THREAD

**Issue by chross** [tobya/DocTo#204] opened 2022-11-25 12:50 UTC
Hi!
I still have an issue with powerpoint.
The error message from the log is as follows:
```
[INFO]   [20221125 13:49:26 -]: LogFile Loaded
[INFO]   FileToConvert:C:\docto\tmp\fa78227a921d00273658771095352065952cb483.pptx
[INFO]   OutputFile:C:\docto\tmp\fa78227a921d00273658771095352065952cb483.pdf
[INFO]   Ext32
*******************************************
Error: EOleException  Unspecified error
*******************************************
```

Any idea what the problem might be?
Visio, Excel and Word files will convert successfully.

**Comment by tobya** [comment] 2022-11-25 15:14
Could you please provide the full command line and add -L 10 to the end.  

What is in C:\docto\tmp\fa78227a921d00273658771095352065952cb483.pdf

**Comment by chross** [comment] 2022-11-25 16:04
```
[DEBUG]  Log Level Set To:10
Loading ChooseConverter...
Parameter Count is 18
Converter:MS Powerpoint
[DEBUG]  Log Level Set To:10
[INFO]   Loading Configuration...
[DEBUG]  Parameter Count is 18
[INFO]   [20221125 17:02:52 -]: LogFile Loaded
[INFO]   [20221125 17:02:52 -]: LogFile Loaded
[DEBUG]  Input File is: C:\docto\tmp\fa78227a921d00273658771095352065952cb483.pptx
[INFO]   Output directory: C:\docto\tmp\
[DEBUG]  Type Integer is: 32
[INFO]   Log Level Set To:10
[DEBUG]  Current Directory: C:\inetpub\wwwroot
[DEBUG]  Ready to Execute
[DEBUG]  Executing Conversion ... 
[DEBUG]  Trying to Convert: C:\docto\tmp\fa78227a921d00273658771095352065952cb483.pptx
[INFO]   FileToConvert:C:\docto\tmp\fa78227a921d00273658771095352065952cb483.pptx
[INFO]   OutputFile:C:\docto\tmp\fa78227a921d00273658771095352065952cb483.pdf
[INFO]   Ext32
*******************************************
Error: EOleException  Unspecified error
*******************************************
```


The pdf file does not get generated, there is no ouput file.

Kind Regards

**Comment by tobya** [comment] 2022-11-25 20:07
Are you running from the command line or via a website (php, node etc)?

Can you convert any other pptx files?  Do they all have the same issue.

Can you try with a ppt file? (if you open pptx  in powerpoint and save as ppt )   Does that work?

If you run it in a console window running as administrator does it work?

Can you try and give me as much information as possible about your setup, This is an office error that could be caused by any number ofissues so as much info as possible.

Can you run docto -v  and let me know what the result is.

**Comment by chross** [comment] 2022-11-25 21:47
Hi!
I've set up a Windows Server with IIS and PHP 8. Everything is runnig under a custom user profile, to get everything working I was using the trick from another issue where one had to create the Desktop folder for the system config account.
Office documents are uploaded via POST request and saved in a subfolder of the docto folder (tmp). Then docto is run via shell_exec() with the above mentioned command line.
Word, Excel and Visio files are converted flawlessly, only Powerpoint has its problems.

PPTX and PPT files fail to convert, while other formats DOCX, DOC, XLSX, XLS, VSDX, VSD will convert easily.

docto -v yields
DocTo Version:1.8.39 (Test version )
OfficeApp Version:16

**Comment by tobya** [comment] 2022-11-25 21:59
pptx support is pretty new and experimental.  I'll see if I can get time to do some test and see if I can reproduce any issues.

If word, excel are working its more likely to be something specific to how powerpoint is running on the server.  

When I get some time i'll take  a look at trying to reproduce.

**Comment by chross** [comment] 2022-11-25 22:05
Thanks for your effort. If I can be of any assistance, just let me know.

**Comment by tobya** [comment] 2022-11-25 22:12
I presume  the document itself opens and resaves manually in powerpoint without issues

eg. can you open the pptx or ppt file in powerpoint and saveas or export as a pdf and not get any errors?

**Comment by chross** [comment] 2022-11-25 22:16
That is true. I log on to the server using the same account IIS is running the tasks. Under this user, I can open all files from the /docto/tmp/ folder (after they have been uploaded by the POST request), without problems.

Also, when manually invoking docto on the server, conversion of ppt or pptx files fail as well.

**Comment by tobya** [comment] 2022-11-25 22:28
Let me know if you gather any more information about what works and what doesnt.

**Comment by tobya** [comment] 2023-06-02 12:04
I am going to close this for now, please reopen if more info available

**Closed by tobya** 2023-06-02 12:04 UTC
